**Задание на повторение материала**

1. Создать одномерный массив Numpy под названием a из 12 последовательных целых чисел (чисел от 12 до 24 невключительно).


In [380]:
import numpy as np

In [381]:
a = np.array([i for i in range(12, 24)])
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

2. Создать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах метода reshape число -1.

In [382]:
a.resize(3, 4)
a

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [383]:
a.resize(2, 6)
a

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [384]:
a.resize(4, 3)
a

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [385]:
a.resize(6, 2)
a

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [386]:
a.resize(4, 3)
np.random.shuffle(a)
a

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

3. Создать 5 двумерных массивов разной формы из массива a. Использовать в аргументах метода reshape число -1 (в трех примерах - для обозначения числа столбцов, в двух - для строк).

In [387]:
a = np.array([i for i in range(12, 24)])
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

In [388]:
np.reshape(a, (2, -1))

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [389]:
np.reshape(a, (3, -1))

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [390]:
np.reshape(a, (6, -1))

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [391]:
np.reshape(a, (-1, 3))

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [392]:
np.reshape(a, (-1, 2))

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

4. Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?

**Ответ:** Нет, т.к. массив будет с двумя индексами (номер строки (от 0 до 11) и 0 - номер столбца).

5. Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой из нормального распределения со средним, равным 0 и среднеквадратичным отклонением, равным 1.0.

Применяем **numpy.random.randn** - случайные числа с нормальным распределением
(среднее значение = 0, среднеквадратичное отклонение = 1)

In [393]:
s = np.random.randn(3, 4)
s

array([[ 0.07983181, -0.1595165 ,  0.02222183, -0.42779291],
       [-0.53181741, -0.1174755 ,  0.2220789 , -0.7679765 ],
       [ 0.1424646 , -0.03465218,  1.13433927, -0.10474555]])

In [394]:
s.size

12

Для наглядности покажем размерность исходного массива:

In [395]:
s.shape

(3, 4)

Получить из этого массива одномерный массив с таким же атрибутом size, как и исходный массив.

Применяем flatten - получить из многомерного массива одномерный массив

In [396]:
s = s.flatten()
s

array([ 0.07983181, -0.1595165 ,  0.02222183, -0.42779291, -0.53181741,
       -0.1174755 ,  0.2220789 , -0.7679765 ,  0.1424646 , -0.03465218,
        1.13433927, -0.10474555])

In [397]:
s.size

12

In [398]:
s.shape

(12,)

Мы получили из двумерного массива одномерный с таким же атрибутом size, как и исходный массив.

6. Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с интервалом 2.

In [399]:
a = np.array([i for i in range(20, 0, -2)])
a

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

7. Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1 невключительно с интервалом 2. В чем разница между массивами a и b?

In [400]:
b = np.arange(20, 1, -2)
b

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

In [401]:
type(a)

numpy.ndarray

In [402]:
type(b)

numpy.ndarray

In [403]:
a.dtype

dtype('int32')

In [404]:
b.dtype

dtype('int32')

In [405]:
a.ndim

1

In [406]:
b.ndim

1

In [407]:
a.shape

(10,)

In [408]:
b.shape

(10,)

В чем разница между массивами a и b?

**Ответ:** Разница в массивах a и b в моем случае только в методах создания. В остальном они одинаковые.

8. Вертикально соединить массивы a и b. 

a - двумерный массив из нулей, число строк которого больше 1 и на 1 меньше, чем число строк двумерного массива b, состоящего из единиц. 

Итоговый массив v должен иметь атрибут size, равный 10.

In [409]:
a = np.zeros((2, 2))
a

array([[0., 0.],
       [0., 0.]])

In [410]:
b = np.ones((3, 2))
b

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [411]:
v = np.vstack((a, b))
v

array([[0., 0.],
       [0., 0.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [412]:
v.size

10

9. Создать одномерный массив а, состоящий из последовательности целых чисел от 0 до 12.

P.S. правая граница явно не включается в массив (этого нет в условии), т.к. 13 элементов в двумерном массиве быть не может (далее в задаче необходимо поменять форму исходного массива).

In [413]:
a = np.arange(0, 12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

Поменять форму этого массива, чтобы получилась матрица A (двумерный массив Numpy), состоящая из 4 строк и 3 столбцов.

In [414]:
a.resize(4, 3)
A = np.array(a)
A

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

Получить матрицу At путем транспонирования матрицы A.

In [415]:
At = A.T
At

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

 Получить матрицу B, умножив матрицу A на матрицу At с помощью матричного умножения.

In [416]:
B = np.dot(A, At)
B

array([[  5,  14,  23,  32],
       [ 14,  50,  86, 122],
       [ 23,  86, 149, 212],
       [ 32, 122, 212, 302]])

Какой размер имеет матрица B?

In [417]:
B.size

16

Получится ли вычислить обратную матрицу для матрицы B и почему?

In [418]:
np.linalg.det(B)

0.0

**Ответ**: обратной матрицы для матрицы В нет, т.к. определитель равен нулю.

10. Инициализируйте генератор случайных числе с помощью объекта seed, равного 42

In [419]:
np.random.seed(42)

11. Создайте одномерный массив c, составленный из последовательности 16-ти случайных равномерно распределенных целых чисел от 0 до 16 невключительно.

In [420]:
с = np.random.randint(0, 16, 16)
с

array([ 6,  3, 12, 14, 10,  7, 12,  4,  6,  9,  2,  6, 10, 10,  7,  4])

12. Поменяйте его форму так, чтобы получилась квадратная матрица C.

In [421]:
с.resize(4, 4)
C = np.array(с)
C

array([[ 6,  3, 12, 14],
       [10,  7, 12,  4],
       [ 6,  9,  2,  6],
       [10, 10,  7,  4]])

Получите матрицу D, поэлементно прибавив матрицу B из предыдущего вопроса к матрице C, умноженной на 10.

In [422]:
D = B + C * 10
D

array([[ 65,  44, 143, 172],
       [114, 120, 206, 162],
       [ 83, 176, 169, 272],
       [132, 222, 282, 342]])

Вычислите определитель, ранг и обратную матрицу D_inv для D.

In [423]:
# Определитель:
np.linalg.det(D)

-28511999.999999944

In [424]:
# Ранг
np.linalg.matrix_rank(D)

4

In [425]:
# Обратная матрица
D_inv = np.linalg.inv(D)
D_inv

array([[ 0.00935396,  0.04486532,  0.05897517, -0.07286055],
       [-0.01503577, -0.00122896, -0.00192971,  0.00967873],
       [-0.00356692, -0.01782828, -0.04152146,  0.04326178],
       [ 0.00909091, -0.00181818,  0.01272727, -0.01090909]])

13. Приравняйте к нулю отрицательные числа в матрице D_inv, а положительные - к единице.

In [426]:
import pandas as pd

In [427]:
df = pd.DataFrame(D_inv, columns=['a', 'b', 'c', 'd'])
df

a         b         c         d
0  0.009354  0.044865  0.058975 -0.072861
1 -0.015036 -0.001229 -0.001930  0.009679
2 -0.003567 -0.017828 -0.041521  0.043262
3  0.009091 -0.001818  0.012727 -0.010909

In [428]:
df['a'] = np.where((df.a < 0), 0, df.a)
df['b'] = np.where((df.b < 0), 0, df.b)
df['c'] = np.where((df.c < 0), 0, df.c)
df['d'] = np.where((df.d < 0), 0, df.d)
df['a'] = np.where((df.a > 0), 1, df.a)
df['b'] = np.where((df.b > 0), 1, df.b)
df['c'] = np.where((df.c > 0), 1, df.c)
df['d'] = np.where((df.d > 0), 1, df.d)
print(df)

     a    b    c    d
0  1.0  1.0  1.0  0.0
1  0.0  0.0  0.0  1.0
2  0.0  0.0  0.0  1.0
3  1.0  0.0  1.0  0.0


Убедитесь, что в матрице D_inv остались только нули и единицы.

In [429]:
D_inv

array([[1., 1., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [1., 0., 1., 0.]])

С помощью функции numpy.where, используя матрицу D_inv в качестве маски, а матрицы B и C - в качестве источников данных, получите матрицу E размером 4x4.  Элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 1, должны быть равны соответствующему элементу матрицы B, а элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 0, должны быть равны соответствующему элементу матрицы C.

In [430]:
B

array([[  5,  14,  23,  32],
       [ 14,  50,  86, 122],
       [ 23,  86, 149, 212],
       [ 32, 122, 212, 302]])

In [431]:
C

array([[ 6,  3, 12, 14],
       [10,  7, 12,  4],
       [ 6,  9,  2,  6],
       [10, 10,  7,  4]])

In [432]:
E = np.where(D_inv, B, C)
E

array([[  5,  14,  23,  14],
       [ 10,   7,  12, 122],
       [  6,   9,   2, 212],
       [ 32,  10, 212,   4]])